name: Cache
on:
  push:
    branches: [main]
jobs:
  darwin:
    name: Darwin
    runs-on: macos-latest

    strategy:
      # continue if one host fails
      fail-fast: false

      matrix:
        host: [brian-air]

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install nix
        uses: cachix/install-nix-action@v31

      - name: Setup Cachix
        uses: cachix/cachix-action@v16
        with:
          name: bfogarty
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - name: Build and cache nix-darwin configuration
        run: nix build .#darwinConfigurations.${{ matrix.host }}.system
