name: Cache
on:
  push:
    # TODO: remove before merge
    branches: [main, brian/cachix]
jobs:
  darwin:
    strategy:
      matrix:
        host: [brian-mbp-2, Thyme-M5772J33W1]
    name: Cache
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v19
      - uses: cachix/cachix-action@v12
        with:
          name: bfogarty
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - run: nix build .#darwinConfigurations.${{ matrix.host }}.system
