name: Cache
on:
  push:
    # TODO: remove before merge
    branches: [main, brian/cachix]
jobs:
  cache:
    name: Cache
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v19
      - uses: cachix/cachix-action@v12
        with:
          name: bfogarty
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
